name: Check backend
on: 
  push:
    branches:
      - "**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: print env
        run: echo ${{ secrets.ENVIRONMENT }}
        env: 
          ENVIRONMENT: "test"
      - name: Installing poetry
        run: pip3 install poetry
      - name: Env do not create 
        run: poetry config virtualenvs.create false
      - name: Poetry install
        run: poetry install --no-interaction --no-ansi --no-root
      - name: Formatting test
        run: black *.py ./**/*.py --check
